#ifndef TASKMANAGER_TESTS_TEST_UTILS_COMMON_H_
#define TASKMANAGER_TESTS_TEST_UTILS_COMMON_H_

using namespace task_manager;  // NOLINT: Testing purpose

#endif  // TASKMANAGER_TESTS_TEST_UTILS_COMMON_H_
